name: Deploy

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    name: Upload Package
    runs-on: ubuntu-latest
    steps:
    - name: check cgroup
      run: |
        cd /sys/fs/cgroup
        ls
